apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: juandariasgomez-dev
  labels:
    app: mysql-db
spec:
  type: ClusterIP
  selector:
    app: mysql-db
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306