apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: juandariasgomez-dev
type: Opaque
stringData:
  DB_HOST: mysql
  DB_NAME: turnosdb
  DB_PASS: rootpassword
  DB_PORT: "3306"
  DB_USER: root
  MYSQL_PASSWORD: rootpassword
  MYSQL_ROOT_PASSWORD: rootpassword
  PORT: "8080"