apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: juandariasgomez-dev
type: Opaque
data:
  DB_HOST: 
  DB_NAME: 
  DB_PASS: 
  DB_PORT: 
  DB_USER: 
  MYSQL_PASSWORD: 
  MYSQL_ROOT_PASSWORD: 
  PORT: 
