apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: turnos-system-service
  namespace: juandariasgomez-dev
  labels:
    app: turnos-system
spec:
  host: turnos.jda96devops.site
  to:
    kind: Service
    name: turnos-system-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None